/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package GUI;

import cpit.GenerateReport;
import static cpit.login.login;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Font;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.border.EmptyBorder;

/**
 *
 * @author noufa
 */
    public class ReportWindow extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ReportWindow.class.getName());

    private JTextArea reportArea;

    private final Color ACCENT = new Color(59, 130, 246);
    private final Color TEXT_LIGHT = Color.WHITE;
    private final Color CARD_BG = new Color(30, 41, 59);
    private final Color FIELD_BG = new Color(26, 39, 58);

    public ReportWindow() {
        setTitle("Generate Report");
        setSize(1400, 900);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(EXIT_ON_CLOSE);

        setContentPane(new GradientPanel());
        setLayout(null);

        buildUI();
        generateAndDisplayReport();
    }

    private void buildUI() {

        JPanel card = new JPanel(null);
        card.setBackground(CARD_BG);
        card.setBounds(100, 60, 1200, 750);
        card.setBorder(BorderFactory.createLineBorder(new Color(44, 62, 80), 2));
        add(card);

        ShadowLabel title = new ShadowLabel("INVENTORY REPORT");
        title.setFont(new Font("Tw Cen MT Condensed", Font.BOLD, 48));
        title.setBounds(450, 20, 900, 60);
        card.add(title);

        // Back button
        JButton backBtn = accentButton("Back");
        backBtn.setBounds(30, 30, 120, 40);
        backBtn.addActionListener(e -> {
            new Dashboard1().setVisible(true);
            dispose();
        });
        card.add(backBtn);

        reportArea = new JTextArea();
        reportArea.setEditable(false);
        reportArea.setFont(new Font("Consolas", Font.PLAIN, 16));
        reportArea.setBackground(FIELD_BG);
        reportArea.setForeground(Color.WHITE);
        reportArea.setBorder(new EmptyBorder(15, 15, 15, 15));

        // Scrollable container for ReportWindow
        JScrollPane scrollPane = new JScrollPane(reportArea);
        scrollPane.setBounds(80, 120, 1040, 580);
        scrollPane.getViewport().setBackground(FIELD_BG);
        scrollPane.setBorder(BorderFactory.createLineBorder(
                new Color(55, 65, 81), 1));
        card.add(scrollPane);
    }

    private void generateAndDisplayReport() {

        try {

            int managerID = login();
            GenerateReport service = new GenerateReport();
            String report= service.generateInventoryReport(managerID);
            reportArea.setText(report);

        } catch (Exception e) {
            String errorMsg= "Error generating report.";
            reportArea.setText(errorMsg);
            JOptionPane.showMessageDialog(this,errorMsg);
            e.printStackTrace();
        }
    }

    private JButton accentButton(String text) {
        JButton b = new JButton(text);
        b.setBackground(ACCENT);
        b.setForeground(new Color(15, 23, 42));
        b.setFont(new Font("Segoe UI", Font.BOLD, 16));
        b.setFocusPainted(false);
        b.setBorderPainted(false);
        b.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        b.setBorder(new EmptyBorder(8, 18, 8, 18));
        return b;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ReportWindow().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}


